### ISSUE TITLE
Wrong number of positional arguments in financial_data_scrapper

### ISSUE THREAD

**Issue by oort77** [mldsveda/PyScrappy#7]
Simple test gives a mistake. What could be a cause?

<img width="1714" alt="Screenshot 2021-07-30 at 17 12 07" src="https://user-images.githubusercontent.com/73858914/127666684-894be53b-6734-43ef-81e0-8ba180a974b5.png">

**Comment by mldsveda** [comment]
@oort77 Thanks for using our web-scraping package and pointing out an issue.
There is a minor bug that we are currently working on, particularly in the Stock Scrapper.
This issue is occurring because of sudden changes in the Stock website from where we are fetching the data, we are looking into the issue and will be soon rolling out the latest version with newer options, faster performance, and bug fixes.
Thank you for raising this issue as it helps in keeping the package up to date.
